export const timezones = [
  "Pacific/Midway (GMT-11)",
  "Pacific/Niue (GMT-11)",
  "Pacific/Pago Pago (GMT-11)",
  "Pacific/Honolulu (GMT-10)",
  "Pacific/Rarotonga (GMT-10)",
  "Pacific/Tahiti (GMT-10)",
  "Pacific/Marquesas (GMT-9.5)",
  "America/Adak (GMT-9)",
  "Pacific/Gambier (GMT-9)",
  "America/Anchorage (GMT-8)",
  "America/Juneau (GMT-8)",
  "America/Metlakatla (GMT-8)",
  "America/Nome (GMT-8)",
  "America/Sitka (GMT-8)",
  "America/Yakutat (GMT-8)",
  "Pacific/Pitcairn (GMT-8)",
  "America/Creston (GMT-7)",
  "America/Dawson (GMT-7)",
  "America/Dawson Creek (GMT-7)",
  "America/Fort Nelson (GMT-7)",
  "America/Hermosillo (GMT-7)",
  "America/Los Angeles (GMT-7)",
  "America/Mazatlan (GMT-7)",
  "America/Phoenix (GMT-7)",
  "America/Tijuana (GMT-7)",
  "America/Vancouver (GMT-7)",
  "America/Whitehorse (GMT-7)",
  "America/Bahia Banderas (GMT-6)",
  "America/Belize (GMT-6)",
  "America/Boise (GMT-6)",
  "America/Cambridge Bay (GMT-6)",
  "America/Chihuahua (GMT-6)",
  "America/Costa Rica (GMT-6)",
  "America/Denver (GMT-6)",
  "America/Edmonton (GMT-6)",
  "America/El Salvador (GMT-6)",
  "America/Guatemala (GMT-6)",
  "America/Inuvik (GMT-6)",
  "America/Managua (GMT-6)",
  "America/Merida (GMT-6)",
  "America/Mexico City (GMT-6)",
  "America/Monterrey (GMT-6)",
  "America/Regina (GMT-6)",
  "America/Swift Current (GMT-6)",
  "America/Tegucigalpa (GMT-6)",
  "America/Yellowknife (GMT-6)",
  "Pacific/Easter (GMT-6)",
  "Pacific/Galapagos (GMT-6)",
  "America/Atikokan (GMT-5)",
  "America/Bogota (GMT-5)",
  "America/Cancun (GMT-5)",
  "America/Cayman (GMT-5)",
  "America/Chicago (GMT-5)",
  "America/Eirunepe (GMT-5)",
  "America/Guayaquil (GMT-5)",
  "America/Indiana/Knox (GMT-5)",
  "America/Indiana/Tell City (GMT-5)",
  "America/Jamaica (GMT-5)",
  "America/Lima (GMT-5)",
  "America/Matamoros (GMT-5)",
  "America/Menominee (GMT-5)",
  "America/North Dakota/Beulah (GMT-5)",
  "America/North Dakota/Center (GMT-5)",
  "America/North Dakota/New Salem (GMT-5)",
  "America/Ojinaga (GMT-5)",
  "America/Panama (GMT-5)",
  "America/Rainy River (GMT-5)",
  "America/Rankin Inlet (GMT-5)",
  "America/Resolute (GMT-5)",
  "America/Rio Branco (GMT-5)",
  "America/Winnipeg (GMT-5)",
  "America/Anguilla (GMT-4)",
  "America/Antigua (GMT-4)",
  "America/Aruba (GMT-4)",
  "America/Asuncion (GMT-4)",
  "America/Barbados (GMT-4)",
  "America/Blanc-Sablon (GMT-4)",
  "America/Boa Vista (GMT-4)",
  "America/Campo Grande (GMT-4)",
  "America/Caracas (GMT-4)",
  "America/Cuiaba (GMT-4)",
  "America/Curacao (GMT-4)",
  "America/Detroit (GMT-4)",
  "America/Dominica (GMT-4)",
  "America/Grand Turk (GMT-4)",
  "America/Grenada (GMT-4)",
  "America/Guadeloupe (GMT-4)",
  "America/Guyana (GMT-4)",
  "America/Havana (GMT-4)",
  "America/Indiana/Indianapolis (GMT-4)",
  "America/Indiana/Marengo (GMT-4)",
  "America/Indiana/Petersburg (GMT-4)",
  "America/Indiana/Vevay (GMT-4)",
  "America/Indiana/Vincennes (GMT-4)",
  "America/Indiana/Winamac (GMT-4)",
  "America/Iqaluit (GMT-4)",
  "America/Kentucky/Louisville (GMT-4)",
  "America/Kentucky/Monticello (GMT-4)",
  "America/Kralendijk (GMT-4)",
  "America/La Paz (GMT-4)",
  "America/Lower Princes (GMT-4)",
  "America/Manaus (GMT-4)",
  "America/Marigot (GMT-4)",
  "America/Martinique (GMT-4)",
  "America/Montserrat (GMT-4)",
  "America/Nassau (GMT-4)",
  "America/New York (GMT-4)",
  "America/Nipigon (GMT-4)",
  "America/Pangnirtung (GMT-4)",
  "America/Port of Spain (GMT-4)",
  "America/Port-au-Prince (GMT-4)",
  "America/Porto Velho (GMT-4)",
  "America/Puerto Rico (GMT-4)",
  "America/Santiago (GMT-4)",
  "America/Santo Domingo (GMT-4)",
  "America/St Barthelemy (GMT-4)",
  "America/St Kitts (GMT-4)",
  "America/St Lucia (GMT-4)",
  "America/St Thomas (GMT-4)",
  "America/St Vincent (GMT-4)",
  "America/Thunder Bay (GMT-4)",
  "America/Toronto (GMT-4)",
  "America/Tortola (GMT-4)",
  "America/Araguaina (GMT-3)",
  "America/Argentina/Buenos Aires (GMT-3)",
  "America/Argentina/Catamarca (GMT-3)",
  "America/Argentina/Cordoba (GMT-3)",
  "America/Argentina/Jujuy (GMT-3)",
  "America/Argentina/La Rioja (GMT-3)",
  "America/Argentina/Mendoza (GMT-3)",
  "America/Argentina/Rio Gallegos (GMT-3)",
  "America/Argentina/Salta (GMT-3)",
  "America/Argentina/San Juan (GMT-3)",
  "America/Argentina/San Luis (GMT-3)",
  "America/Argentina/Tucuman (GMT-3)",
  "America/Argentina/Ushuaia (GMT-3)",
  "America/Bahia (GMT-3)",
  "America/Belem (GMT-3)",
  "America/Cayenne (GMT-3)",
  "America/Fortaleza (GMT-3)",
  "America/Glace Bay (GMT-3)",
  "America/Goose Bay (GMT-3)",
  "America/Halifax (GMT-3)",
  "America/Maceio (GMT-3)",
  "America/Moncton (GMT-3)",
  "America/Montevideo (GMT-3)",
  "America/Paramaribo (GMT-3)",
  "America/Punta Arenas (GMT-3)",
  "America/Recife (GMT-3)",
  "America/Santarem (GMT-3)",
  "America/Sao Paulo (GMT-3)",
  "America/Thule (GMT-3)",
  "Antarctica/Palmer (GMT-3)",
  "Antarctica/Rothera (GMT-3)",
  "Atlantic/Bermuda (GMT-3)",
  "Atlantic/Stanley (GMT-3)",
  "America/St Johns (GMT-2.5)",
  "America/Miquelon (GMT-2)",
  "America/Noronha (GMT-2)",
  "Atlantic/South Georgia (GMT-2)",
  "America/Nuuk (GMT-1)",
  "America/Scoresbysund (GMT-1)",
  "Atlantic/Cape Verde (GMT-1)",
  "Africa/Abidjan (GMT+0)",
  "Africa/Accra (GMT+0)",
  "Africa/Bamako (GMT+0)",
  "Africa/Banjul (GMT+0)",
  "Africa/Bissau (GMT+0)",
  "Africa/Conakry (GMT+0)",
  "Africa/Dakar (GMT+0)",
  "Africa/Freetown (GMT+0)",
  "Africa/Lome (GMT+0)",
  "Africa/Monrovia (GMT+0)",
  "Africa/Nouakchott (GMT+0)",
  "Africa/Ouagadougou (GMT+0)",
  "Africa/Sao Tome (GMT+0)",
  "America/Danmarkshavn (GMT+0)",
  "Atlantic/Azores (GMT+0)",
  "Atlantic/Reykjavik (GMT+0)",
  "Atlantic/St Helena (GMT+0)",
  "Africa/Algiers (GMT+1)",
  "Africa/Bangui (GMT+1)",
  "Africa/Brazzaville (GMT+1)",
  "Africa/Casablanca (GMT+1)",
  "Africa/Douala (GMT+1)",
  "Africa/El Aaiun (GMT+1)",
  "Africa/Kinshasa (GMT+1)",
  "Africa/Lagos (GMT+1)",
  "Africa/Libreville (GMT+1)",
  "Africa/Luanda (GMT+1)",
  "Africa/Malabo (GMT+1)",
  "Africa/Ndjamena (GMT+1)",
  "Africa/Niamey (GMT+1)",
  "Africa/Porto-Novo (GMT+1)",
  "Africa/Tunis (GMT+1)",
  "Atlantic/Canary (GMT+1)",
  "Atlantic/Faroe (GMT+1)",
  "Atlantic/Madeira (GMT+1)",
  "Europe/Dublin (GMT+1)",
  "Europe/Guernsey (GMT+1)",
  "Europe/Isle of Man (GMT+1)",
  "Europe/Jersey (GMT+1)",
  "Europe/Lisbon (GMT+1)",
  "Europe/London (GMT+1)",
  "Africa/Blantyre (GMT+2)",
  "Africa/Bujumbura (GMT+2)",
  "Africa/Ceuta (GMT+2)",
  "Africa/Gaborone (GMT+2)",
  "Africa/Harare (GMT+2)",
  "Africa/Johannesburg (GMT+2)",
  "Africa/Juba (GMT+2)",
  "Africa/Khartoum (GMT+2)",
  "Africa/Kigali (GMT+2)",
  "Africa/Lubumbashi (GMT+2)",
  "Africa/Lusaka (GMT+2)",
  "Africa/Maputo (GMT+2)",
  "Africa/Maseru (GMT+2)",
  "Africa/Mbabane (GMT+2)",
  "Africa/Tripoli (GMT+2)",
  "Africa/Windhoek (GMT+2)",
  "Antarctica/Troll (GMT+2)",
  "Arctic/Longyearbyen (GMT+2)",
  "Europe/Amsterdam (GMT+2)",
  "Europe/Andorra (GMT+2)",
  "Europe/Belgrade (GMT+2)",
  "Europe/Berlin (GMT+2)",
  "Europe/Bratislava (GMT+2)",
  "Europe/Brussels (GMT+2)",
  "Europe/Budapest (GMT+2)",
  "Europe/Busingen (GMT+2)",
  "Europe/Copenhagen (GMT+2)",
  "Europe/Gibraltar (GMT+2)",
  "Europe/Kaliningrad (GMT+2)",
  "Europe/Ljubljana (GMT+2)",
  "Europe/Luxembourg (GMT+2)",
  "Europe/Madrid (GMT+2)",
  "Europe/Malta (GMT+2)",
  "Europe/Monaco (GMT+2)",
  "Europe/Oslo (GMT+2)",
  "Europe/Paris (GMT+2)",
  "Europe/Podgorica (GMT+2)",
  "Europe/Prague (GMT+2)",
  "Europe/Rome (GMT+2)",
  "Europe/San Marino (GMT+2)",
  "Europe/Sarajevo (GMT+2)",
  "Europe/Skopje (GMT+2)",
  "Europe/Stockholm (GMT+2)",
  "Europe/Tirane (GMT+2)",
  "Europe/Vaduz (GMT+2)",
  "Europe/Vatican (GMT+2)",
  "Europe/Vienna (GMT+2)",
  "Europe/Warsaw (GMT+2)",
  "Europe/Zagreb (GMT+2)",
  "Europe/Zurich (GMT+2)",
  "Africa/Addis Ababa (GMT+3)",
  "Africa/Asmara (GMT+3)",
  "Africa/Cairo (GMT+3)",
  "Africa/Dar es Salaam (GMT+3)",
  "Africa/Djibouti (GMT+3)",
  "Africa/Kampala (GMT+3)",
  "Africa/Mogadishu (GMT+3)",
  "Africa/Nairobi (GMT+3)",
  "Antarctica/Syowa (GMT+3)",
  "Asia/Aden (GMT+3)",
  "Asia/Amman (GMT+3)",
  "Asia/Baghdad (GMT+3)",
  "Asia/Bahrain (GMT+3)",
  "Asia/Beirut (GMT+3)",
  "Asia/Damascus (GMT+3)",
  "Asia/Famagusta (GMT+3)",
  "Asia/Gaza (GMT+3)",
  "Asia/Hebron (GMT+3)",
  "Asia/Jerusalem (GMT+3)",
  "Asia/Kuwait (GMT+3)",
  "Asia/Nicosia (GMT+3)",
  "Asia/Qatar (GMT+3)",
  "Asia/Riyadh (GMT+3)",
  "Europe/Athens (GMT+3)",
  "Europe/Bucharest (GMT+3)",
  "Europe/Chisinau (GMT+3)",
  "Europe/Helsinki (GMT+3)",
  "Europe/Istanbul (GMT+3)",
  "Europe/Kirov (GMT+3)",
  "Europe/Kyiv (GMT+3)",
  "Europe/Mariehamn (GMT+3)",
  "Europe/Minsk (GMT+3)",
  "Europe/Moscow (GMT+3)",
  "Europe/Riga (GMT+3)",
  "Europe/Simferopol (GMT+3)",
  "Europe/Sofia (GMT+3)",
  "Europe/Tallinn (GMT+3)",
  "Europe/Uzhgorod (GMT+3)",
  "Europe/Vilnius (GMT+3)",
  "Europe/Volgograd (GMT+3)",
  "Europe/Zaporozhye (GMT+3)",
  "Indian/Antananarivo (GMT+3)",
  "Indian/Comoro (GMT+3)",
  "Indian/Mayotte (GMT+3)",
  "Asia/Tehran (GMT+3.5)",
  "Asia/Baku (GMT+4)",
  "Asia/Dubai (GMT+4)",
  "Asia/Muscat (GMT+4)",
  "Asia/Tbilisi (GMT+4)",
  "Asia/Yerevan (GMT+4)",
  "Europe/Astrakhan (GMT+4)",
  "Europe/Samara (GMT+4)",
  "Europe/Saratov (GMT+4)",
  "Europe/Ulyanovsk (GMT+4)",
  "Indian/Mahe (GMT+4)",
  "Indian/Mauritius (GMT+4)",
  "Indian/Reunion (GMT+4)",
  "Asia/Kabul (GMT+4.5)",
  "Antarctica/Mawson (GMT+5)",
  "Antarctica/Vostok (GMT+5)",
  "Asia/Almaty (GMT+5)",
  "Asia/Aqtau (GMT+5)",
  "Asia/Aqtobe (GMT+5)",
  "Asia/Ashgabat (GMT+5)",
  "Asia/Atyrau (GMT+5)",
  "Asia/Dushanbe (GMT+5)",
  "Asia/Karachi (GMT+5)",
  "Asia/Oral (GMT+5)",
  "Asia/Qostanay (GMT+5)",
  "Asia/Qyzylorda (GMT+5)",
  "Asia/Samarkand (GMT+5)",
  "Asia/Tashkent (GMT+5)",
  "Asia/Yekaterinburg (GMT+5)",
  "Indian/Kerguelen (GMT+5)",
  "Indian/Maldives (GMT+5)",
  "Asia/Colombo (GMT+5.5)",
  "Asia/Kolkata (GMT+5.5)",
  "Asia/Kathmandu (GMT+5.75)",
  "Asia/Bishkek (GMT+6)",
  "Asia/Dhaka (GMT+6)",
  "Asia/Omsk (GMT+6)",
  "Asia/Thimphu (GMT+6)",
  "Asia/Urumqi (GMT+6)",
  "Indian/Chagos (GMT+6)",
  "Asia/Yangon (GMT+6.5)",
  "Indian/Cocos (GMT+6.5)",
  "Antarctica/Davis (GMT+7)",
  "Asia/Bangkok (GMT+7)",
  "Asia/Barnaul (GMT+7)",
  "Asia/Ho Chi Minh (GMT+7)",
  "Asia/Hovd (GMT+7)",
  "Asia/Jakarta (GMT+7)",
  "Asia/Krasnoyarsk (GMT+7)",
  "Asia/Novokuznetsk (GMT+7)",
  "Asia/Novosibirsk (GMT+7)",
  "Asia/Phnom Penh (GMT+7)",
  "Asia/Pontianak (GMT+7)",
  "Asia/Tomsk (GMT+7)",
  "Asia/Vientiane (GMT+7)",
  "Indian/Christmas (GMT+7)",
  "Antarctica/Casey (GMT+8)",
  "Asia/Brunei (GMT+8)",
  "Asia/Choibalsan (GMT+8)",
  "Asia/Hong Kong (GMT+8)",
  "Asia/Irkutsk (GMT+8)",
  "Asia/Kuala Lumpur (GMT+8)",
  "Asia/Kuching (GMT+8)",
  "Asia/Macau (GMT+8)",
  "Asia/Makassar (GMT+8)",
  "Asia/Manila (GMT+8)",
  "Asia/Shanghai (GMT+8)",
  "Asia/Singapore (GMT+8)",
  "Asia/Taipei (GMT+8)",
  "Asia/Ulaanbaatar (GMT+8)",
  "Australia/Perth (GMT+8)",
  "Australia/Eucla (GMT+8.75)",
  "Asia/Chita (GMT+9)",
  "Asia/Dili (GMT+9)",
  "Asia/Jayapura (GMT+9)",
  "Asia/Khandyga (GMT+9)",
  "Asia/Pyongyang (GMT+9)",
  "Asia/Seoul (GMT+9)",
  "Asia/Tokyo (GMT+9)",
  "Asia/Yakutsk (GMT+9)",
  "Pacific/Palau (GMT+9)",
  "Australia/Adelaide (GMT+9.5)",
  "Australia/Broken Hill (GMT+9.5)",
  "Australia/Darwin (GMT+9.5)",
  "Antarctica/DumontDUrville (GMT+10)",
  "Antarctica/Macquarie (GMT+10)",
  "Asia/Ust-Nera (GMT+10)",
  "Asia/Vladivostok (GMT+10)",
  "Australia/Brisbane (GMT+10)",
  "Australia/Hobart (GMT+10)",
  "Australia/Lindeman (GMT+10)",
  "Australia/Melbourne (GMT+10)",
  "Australia/Sydney (GMT+10)",
  "Pacific/Chuuk (GMT+10)",
  "Pacific/Guam (GMT+10)",
  "Pacific/Port Moresby (GMT+10)",
  "Pacific/Saipan (GMT+10)",
  "Australia/Lord Howe (GMT+10.5)",
  "Asia/Magadan (GMT+11)",
  "Asia/Sakhalin (GMT+11)",
  "Asia/Srednekolymsk (GMT+11)",
  "Pacific/Bougainville (GMT+11)",
  "Pacific/Efate (GMT+11)",
  "Pacific/Guadalcanal (GMT+11)",
  "Pacific/Kosrae (GMT+11)",
  "Pacific/Norfolk (GMT+11)",
  "Pacific/Noumea (GMT+11)",
  "Pacific/Pohnpei (GMT+11)",
  "Antarctica/McMurdo (GMT+12)",
  "Asia/Anadyr (GMT+12)",
  "Asia/Kamchatka (GMT+12)",
  "Pacific/Auckland (GMT+12)",
  "Pacific/Fiji (GMT+12)",
  "Pacific/Funafuti (GMT+12)",
  "Pacific/Kwajalein (GMT+12)",
  "Pacific/Majuro (GMT+12)",
  "Pacific/Nauru (GMT+12)",
  "Pacific/Tarawa (GMT+12)",
  "Pacific/Wake (GMT+12)",
  "Pacific/Wallis (GMT+12)",
  "Pacific/Chatham (GMT+12.75)",
  "Pacific/Apia (GMT+13)",
  "Pacific/Fakaofo (GMT+13)",
  "Pacific/Kanton (GMT+13)",
  "Pacific/Tongatapu (GMT+13)",
  "Pacific/Kiritimati (GMT+14)",
];
